//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_form01 {
	
	
	public partial class Calendar {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Calendar id_calendar;
		
		protected System.Web.UI.WebControls.Label id_today;
		
		protected System.Web.UI.WebControls.Label id_birthday;
	}
}
