//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_form01 {
	
	
	public partial class MView {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.DropDownList id_dropDown;
		
		protected System.Web.UI.WebControls.MultiView id_mview;
		
		protected System.Web.UI.WebControls.View id_view1;
		
		protected System.Web.UI.WebControls.Button id_btn11;
		
		protected System.Web.UI.WebControls.Button id_btn12;
		
		protected System.Web.UI.WebControls.View id_view2;
		
		protected System.Web.UI.WebControls.Button id_btn21;
		
		protected System.Web.UI.WebControls.Button id_btn22;
		
		protected System.Web.UI.WebControls.View id_view3;
		
		protected System.Web.UI.WebControls.Calendar id_calendar;
		
		protected System.Web.UI.WebControls.Button id_btn31;
		
		protected System.Web.UI.WebControls.Button id_btn32;
	}
}
