//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_form01 {
	
	
	public partial class Panel {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Panel id_panel;
		
		protected System.Web.UI.WebControls.DropDownList id_dropDown1;
		
		protected System.Web.UI.WebControls.DropDownList id_dropDown2;
		
		protected System.Web.UI.WebControls.CheckBox id_checkbox;
		
		protected System.Web.UI.WebControls.Button id_btn_refresh;
	}
}
