//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_form01 {
    
    
    public partial class SManager {
        
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected System.Web.UI.ScriptManager id_smanager;
        
        protected System.Web.UI.UpdatePanel id_panel;
        
        protected System.Web.UI.WebControls.Button id_btn;
        
        protected System.Web.UI.WebControls.Label id_label;
        
        protected System.Web.UI.Timer id_timer;
        
        protected System.Web.UI.WebControls.Label id_label_explaination;
        
        protected System.Web.UI.WebControls.Button id_btn2;
        
        protected System.Web.UI.WebControls.Label id_label2;
        
        protected System.Web.UI.UpdateProgress id_progress;
    }
}
