//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_form01 {
	
	
	public partial class Table {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox id_input_name;
		
		protected System.Web.UI.WebControls.TextBox id_input_age;
		
		protected System.Web.UI.WebControls.TextBox id_input_cup;
		
		protected System.Web.UI.HtmlControls.HtmlTableCell id_td_result;
		
		protected System.Web.UI.WebControls.Button id_btn;
	}
}
