//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_form01 {
	
	
	public partial class Validation2 {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Label id_label1;
		
		protected System.Web.UI.WebControls.DropDownList id_dropDown;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator id_validation1;
		
		protected System.Web.UI.WebControls.RadioButtonList id_radioList;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator id_validation2;
		
		protected System.Web.UI.WebControls.TextBox id_input_age;
		
		protected System.Web.UI.WebControls.RangeValidator id_validation3;
		
		protected System.Web.UI.WebControls.TextBox id_input_email;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator id_validation4;
		
		protected System.Web.UI.WebControls.Button id_btn_submit;
		
		protected System.Web.UI.WebControls.ValidationSummary id_validation5;
	}
}
