//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_form01 {
	
	
	public partial class Validation {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox id_input_name;
		
		protected System.Web.UI.WebControls.RequiredFieldValidator id_validation1;
		
		protected System.Web.UI.WebControls.TextBox id_input_age;
		
		protected System.Web.UI.WebControls.RangeValidator id_validation2;
		
		protected System.Web.UI.WebControls.TextBox id_input_password;
		
		protected System.Web.UI.WebControls.TextBox id_input_confirm_password;
		
		protected System.Web.UI.WebControls.CompareValidator id_validation3;
		
		protected System.Web.UI.WebControls.TextBox id_input_email;
		
		protected System.Web.UI.WebControls.RegularExpressionValidator id_validation4;
		
		protected System.Web.UI.WebControls.TextBox id_input_cup;
		
		protected System.Web.UI.WebControls.CustomValidator id_validation5;
		
		protected System.Web.UI.WebControls.ValidationSummary id_validation6;
		
		protected System.Web.UI.WebControls.Button id_btn;
	}
}
